# Conclusion

To conclude, we can say that the disparity in term of wealth, have killed the suspense from a lot of leagues like Spain, Germany, France or Italy. Indeed, in these leagues the richest teams have a faster evolution in terms of mean market value per player than the others and will be champions most of the time.
Regarding the lasts ranks, there is more suspense because a lot of teams with small market value fights to avoid the relegation. It's maybe here where stand the real suspense !


In contrary to most of the leagues the Premier League and the Champions league stay competitive. 

- The Premiere League because it is a grouped evolution in terms of mean market value per player, the disparities are smaller because a lot of teams have a lot of money.

- The Champions league because of the participation of a lot of rich teams with high valuable players, it is very difficult to predict which team will win. This is why this competition is so special and followed all around the world.


